### ISSUE TITLE
Graph for enrolled users

### ISSUE THREAD

**Issue by matthiasAtFernUni** [dualcube/moodle-report_overviewstats#20]
When viewing the graph for enrolled users of a course:
Why do does the plugin show a graph for the last year, if only the data of the last month is displayed? 

![grafik](https://github.com/dualcube/moodle-report_overviewstats/assets/134049816/c6593dc2-456d-416e-a662-6b61f8cd7cc1)

I doubt that this is on purpose. So. Is this a bug, or did we miss to configure something properly?

We are using moodle v.4.1.6 and have v1.5.1 of the plugin installed.

**Comment by moumitahalder** [comment]
This is already requested in this thread https://github.com/dualcube/moodle-report_overviewstats/issues/2

So we are closing this now.
